// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgCreateRecord } from "./types/healthchain/healthchain/tx";
import { MsgUpdateRecord } from "./types/healthchain/healthchain/tx";
import { MsgDeleteRecord } from "./types/healthchain/healthchain/tx";

import { Params as typeParams} from "./types"
import { Record as typeRecord} from "./types"

export { MsgCreateRecord, MsgUpdateRecord, MsgDeleteRecord };

type sendMsgCreateRecordParams = {
  value: MsgCreateRecord,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateRecordParams = {
  value: MsgUpdateRecord,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteRecordParams = {
  value: MsgDeleteRecord,
  fee?: StdFee,
  memo?: string
};


type msgCreateRecordParams = {
  value: MsgCreateRecord,
};

type msgUpdateRecordParams = {
  value: MsgUpdateRecord,
};

type msgDeleteRecordParams = {
  value: MsgDeleteRecord,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgCreateRecord({ value, fee, memo }: sendMsgCreateRecordParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateRecord: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateRecord({ value: MsgCreateRecord.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateRecord: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateRecord({ value, fee, memo }: sendMsgUpdateRecordParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateRecord: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdateRecord({ value: MsgUpdateRecord.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateRecord: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeleteRecord({ value, fee, memo }: sendMsgDeleteRecordParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeleteRecord: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeleteRecord({ value: MsgDeleteRecord.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeleteRecord: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgCreateRecord({ value }: msgCreateRecordParams): EncodeObject {
			try {
				return { typeUrl: "/healthchain.healthchain.MsgCreateRecord", value: MsgCreateRecord.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateRecord: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateRecord({ value }: msgUpdateRecordParams): EncodeObject {
			try {
				return { typeUrl: "/healthchain.healthchain.MsgUpdateRecord", value: MsgUpdateRecord.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateRecord: Could not create message: ' + e.message)
			}
		},
		
		msgDeleteRecord({ value }: msgDeleteRecordParams): EncodeObject {
			try {
				return { typeUrl: "/healthchain.healthchain.MsgDeleteRecord", value: MsgDeleteRecord.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeleteRecord: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Params: getStructure(typeParams.fromPartial({})),
						Record: getStructure(typeRecord.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			HealthchainHealthchain: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;